apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector-service
  namespace: mcp
spec:
  selector:
    app: mcp-inspector
  ports:
  - name: client
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: proxy
    port: 9000
    targetPort: 9000
    protocol: TCP
  type: ClusterIP
